name = "prax-proof"
main = "src/index.ts"
compatibility_date = "2026-06-01"
rules = [{ type = "Text", globs = ["**/*.txt"], fallthrough = true }]

[[d1_databases]]
binding = "DB"
database_name = "proof"
migrations_dir = "migrations"

[[ratelimits]]
name = "INGEST_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 120, period = 60 }

[[ratelimits]]
name = "ADMIN_RATE_LIMITER"
namespace_id = "1002"
simple = { limit = 10, period = 60 }

[triggers]
crons = ["17 * * * *"]
